name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.8.1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release
      
   # - name: Docker-Login
    #  env:
     #   DOCKER_USERNAME: ${{ secrets.dockerusername }}
      #  DOCKER_PASSWORD: ${{ secrets.dockerpassword }}
       # DOCKER_REGISTRY: ${{ secrets.registry }}
      #run: docker login $DOCKER_REGISTRY.azurecr.io --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      
    - name: Docker-Build
      run: docker build -t ssss.azurecr.io/sqpexcnt:dev -f Dockerfile . 
      
    # - name: Docker-Push
    #   run: docker push azurecr.io/sqpexcnt:dev

      
    
  
      
      
