name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.8.1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release
      
   
      
    - name: Docker-Build
      run: docker build -t ssss.azurecr.io/sqpexcnt:dev -f Dockerfile . 

    - name: Docker Login
# You may pin to the exact commit or the version.
# uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      uses: docker/login-action@v1.10.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: ${{ secrets.dockerusername }}
        username: ${{ secrets.dockerpassword }}
        password: ${{ secrets.registry }}
        logout: false

    # - name: Docker-Login
    #   env:
    #     DOCKER_USERNAME: ${{ secrets.dockerusername }}
    #     DOCKER_PASSWORD: ${{ secrets.dockerpassword }}
    #     DOCKER_REGISTRY: ${{ secrets.registry }}
    #   run: docker login $DOCKER_REGISTRY.azurecr.io --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      
    # - name: Docker-Push
    #   run: docker push azurecr.io/sqpexcnt:dev

      
    
  
      
      
